### ISSUE TITLE
Example usage with real values

### ISSUE THREAD

**Issue by leouieda** [scivision/pymap3d#10]
Part of openjournals/joss-reviews#580

It's great that there are examples in the README. They would even more helpful if they included actual values and the expected outcomes so that we can check if we have the correct results. 

This is not a requirement for the review, just a suggestion.

**Comment by scivision** [comment]
I added to the Installation section the commands for each language's self-test routine. It tests every function with degrees and radians, round-trip conversion and some independent cross-checks with PROJ.4

**Comment by leouieda** [comment]
That's great!
