### ISSUE TITLE
Negative altitude in geodetic2ecef

### ISSUE THREAD

**Issue by powersa** [scivision/pymap3d#20]
The function [geodetic2ecef](https://github.com/scivision/pymap3d/blob/master/pymap3d/ecef.py#L58-L97) prohibits negative altitude values [here](https://github.com/scivision/pymap3d/blob/master/pymap3d/ecef.py#L87-L88).

Can you explain the reasoning behind that choice? What if my altitude values are below the ellipsoid, as they are in many locations?

Thanks for your time!

**Comment by scivision** [comment]
This was a mistake on my part, it's fixed.

**Comment by powersa** [comment]
Thanks! Appreciate the library.
