### ISSUE TITLE
ecef2geodetic returns negative altitudes as positive

### ISSUE THREAD

**Issue by SimonTaschke** [scivision/pymap3d#21]
ecef2geodetic returns negative altitudes as positive.
See example code for 1 meter above/below the elliposide.

pymap3d.ecef2geodetic(6378137 - 1, 0, 0, pymap3d.ecef.Ellipsoid('wgs84'), deg=False)
(0.0, 0.0, 1.0)
pymap3d.ecef2geodetic(6378137 + 1, 0, 0, pymap3d.ecef.Ellipsoid('wgs84'), deg=False)
(0.0, 0.0, 1.0)

**Comment by scivision** [comment]
Thanks, the latest commit fixes this issue.

**Comment by SimonTaschke** [comment]
Thank you.
