### ISSUE TITLE
Support for other ECI implementations

### ISSUE THREAD

**Issue by ShashankBice** [scivision/pymap3d#25]
Hi There,
May I know which ECI frame is currently supported now, is it J2000 ? Is there a way (or any plans) to do this for other ECI frames as mentioned on the ECI wikipedia page ?

Thanks
Shashank

**Comment by scivision** [comment]
ECI in Pymap3d is J2000. What other frames are you interested in?

**Comment by scivision** [comment]
Hi @ShashankBice please feel free to reopen then when you know which ECI frame(s) you're interested in. Thanks for reaching out!
