### ISSUE TITLE
Geocentric spherical coordinates are missing?

### ISSUE THREAD

**Issue by asreimer** [scivision/pymap3d#28]
pymap3d is awesome, but seems to be missing a one basic coordinate system that would be useful: spherical ECEF. Currently one can do ecef2geodetic and vice versa, but not sph2geodetic and vice versa.

For example, if a user wants to convert geodetic lat/lon/alt to geocentric lat/lon/alt, they need to convert to XYZ ECEF with geodetic2ecef and then manually calculate spherical geocentric coordinates themselves. Is this by design? If not, would it be acceptable for me to submit a PR adding this to the library?

**Comment by rpavlick** [comment]
I submitted a pull request which contains a function 'geodetic2geocentric' that would do what you want.  It also has geocentric2geodetic. 

See here:
https://github.com/rpavlick/pymap3d/blob/master/pymap3d/latitude.py

**Comment by scivision** [comment]
Thank you. I had found some numerical issues that I was resolving with the PR, I will try to finish this implementation. Thanks and thanks!

**Comment by scivision** [comment]
This work is in the https://github.com/scivision/pymap3d/tree/rcurve branch, based on that PR

**Comment by scivision** [comment]
The geocentric <=> geodetic conversions are added in pymap3d v2.0.1.  Thanks!

**Comment by scivision** [comment]
@asreimer v2.1 was just released, adding many more functions of this sort.

**Comment by asreimer** [comment]
Thank you!
