### ISSUE TITLE
pymap3d 1.2.5 not working with Python 2.7

### ISSUE THREAD

**Issue by auerl** [scivision/pymap3d#3]
Hey @scivision 

We are using pymap3d in a GPS-IMU sensor fusion project and noticed that the latest version crashes with Python 2.7

```
In [1]: import pymap3d
  File "/usr/local/lib/python2.7/dist-packages/pymap3d/__init__.py", line 122
    ecef[i, :] = _rottrip(gst[i]) @ eci[i, :]
                                  ^
SyntaxError: invalid syntax

```

Best wishes and thanks much for open sourcing the code,

auerl

**Comment by scivision** [comment]
Please see https://github.com/scivision/pymap3d/releases/tag/v1.3.0

Thank you

**Comment by auerl** [comment]
Excellent, thanks much for the quick fix :-) @scivision
