### ISSUE TITLE
enu2geodetic returns array of single value floats

### ISSUE THREAD

**Issue by iustin94** [scivision/pymap3d#31]
When I call the enu2geodetic method I would expect that I get returned a tuple[float, float, float] instance. However, when I inspect the result what I get is a tuple of numpy.ndarrays. Is this intended behavior? In the documentation it specifies that the result should be a tuple of floats not arrays.

**Comment by scivision** [comment]
thanks!

**Comment by iustin94** [comment]
So is this fixed? Or stays the same ? ...
